Added chmod and a final-status check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,7 @@ jobs:
           build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
           build-scan-terms-of-use-agree: "yes"
 
+      - run: chmod +x gradlew
       - run: ./scripts/enforce_git_lfs.sh
 
       - run: >
@@ -193,10 +194,23 @@ jobs:
           path: '**/build/outputs/roborazzi/*_compare.png'
           retention-days: 1
 
+  final-status:
+    if: ${{ !cancelled() }}
+    runs-on: ubuntu-latest
+    needs: [check-no-tests, build, android-instrumentation-tests, screenshot-tests]
+    steps:
+      - name: Final status check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+
   publish:
     runs-on: macos-latest
     if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'fletchmckee/liquid' }}
-    needs: [build, android-instrumentation-tests, screenshot-tests]
+    needs: [final-status]
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-java@v5
@@ -227,7 +241,7 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 60
     if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'fletchmckee/liquid' }}
-    needs: [build, android-instrumentation-tests, screenshot-tests]
+    needs: [final-status]
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-java@v5
