Added screenshot testing through Roborazzi. Close to having a release version
- This is another large commit, but most changes aren't in the publishable library but instead the demos along with all of the new screenshot testing logic.
- Only real significant changes to the liquid library was realizing there was no need for the Liquefiable to be public that I can think of, so this was altered to internal. Also read through a lot of compose draw modifier node logic and I don't see any good reason to have the `if (!isAttached)` logic there. If draw calls are happening when detached, it is likely an issue with observing mutable state that we shouldn't be doing.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,9 +10,13 @@ on:
 
 jobs:
   build:
-    name: "build"
     runs-on: ubuntu-latest
     timeout-minutes: 60
+
+    permissions:
+      contents: write
+      pull-requests: write
+
     steps:
       - name: Checkout
         uses: actions/checkout@v5
@@ -40,14 +44,48 @@ jobs:
       - name: Spotless check
         run: ./gradlew spotlessCheck
 
-      - name: Assemble
-        run: ./gradlew assembleDebug
+      - name: Run Roborazzi screenshot tests
+        id: screenshotsverify
+        continue-on-error: true
+        run: ./gradlew verifyRoborazziDebug
+
+      - name: Prevent pushing new screenshots if this is a fork
+        id: checkfork_screenshots
+        continue-on-error: false
+        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Screenshot tests failed, please create a PR in your fork first."
+          echo "Your fork's CI will take screenshots for your fork."
+          exit 1
+
+      - name: Generate new screenshots if verification failed and it's a PR
+        id: screenshotsrecord
+        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew recordRoborazziDebug
+
+      - name: Push new screenshots if available
+        uses: stefanzweifel/git-auto-commit-action@v5
+        if: steps.screenshotsrecord.outcome == 'success'
+        with:
+          file_pattern: '**/screenshots/*.png'
+          disable_globbing: true
+          commit_message: "🤖 Updates screenshots"
 
       - name: Run unit tests
         run: ./gradlew testDebugUnitTest
 
+      - name: Assemble
+        run: ./gradlew assembleDebug
+
+      - name: Upload screenshot results if failed
+        if: ${{ !cancelled() && steps.screenshotsverify.outcome == 'failure' }}
+        uses: actions/upload-artifact@v5
+        with:
+          name: screenshot-test-results
+          path: '**/build/outputs/roborazzi/*_compare.png'
+
   androidTest:
-    name: "androidTest"
     runs-on: ubuntu-latest
     timeout-minutes: 60
     strategy:
@@ -93,11 +131,9 @@ jobs:
           script: ./gradlew connectedDebugAndroidTest --daemon
 
   publish:
-    name: "publish"
     runs-on: ubuntu-latest
     if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'fletchmckee/liquid' }}
-    needs:
-      - build
+    needs: [build, androidTest]
     steps:
       - uses: actions/checkout@v5
       - uses: actions/setup-java@v5
